# Generated by Django 4.2.9 on 2025-03-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shamus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='editlogmodel',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_common',
            field=models.BooleanField(default=False, verbose_name='Виден другим'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='track',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='track',
            name='is_explicit',
            field=models.BooleanField(blank=True, default=False, verbose_name='Откровенная лексика'),
        ),
        migrations.AlterField(
            model_name='track',
            name='is_forbiden',
            field=models.BooleanField(blank=True, default=False, verbose_name='Запрещено'),
        ),
    ]
